<div class="admin__field-label">
    <label>
        <span><?php echo __('Mapping Categories') ?></span>
    </label>
</div>
<div class="admin__field-control" data-role="mapping_categories">
    <table>
        <thead>
            <th>Document Category Value</th><th>Category ID</th></th><th></th>
        </thead>
        <tbody data-bind="foreach: rowData">
            <tr data-bind="attr: {'data-id': rowId}">
                <td><input type="text" name="field_key" data-bind="value: key, event: {keyup: parentModel.changeValue}, attr: {'data-id': rowId}"></td>
                <td><input type="text" name="field_value" data-bind="value: value, event: {keyup: parentModel.changeValue}, attr: {'data-id': rowId}"></td>
                <td><span data-bind="click: parentModel.actionRemove, attr: {'data-id': rowId}"><?php echo __('Remove') ?></span></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">
                    <span data-bind="click: actionAdd"><?php echo __('Add') ?></span>
                </td>
            </tr>
        </tfoot>
    </table>

    <div afterRender="decodeValueString"></div>
</div>

<script>
    require([
        'jquery',
        'Tereta_Import/js/view/mapValues'
    ], function ($, importAttributes) {
        $('[data-role="mapping_categories"]').each(function (index, element) {
            importAttributes({fieldCode: 'mapping_categories'}, element);
        });
    });
</script>
