<div class="admin__field-label">
    <label>
        <span><?php echo __('Description of the input fields') ?></span>
    </label>
</div>
<div class="admin__field-control">
    <ul>
        <li>
            <?php echo __('The "manage_stock" field is the "Manage Stock" value') ?>
        </li>
        <li>
            <?php echo __('The "is_in_stock" field is the "Stock Status" value') ?>
        </li>
        <li>
            <?php echo __('The "use_config_manage_stock" field is the "Use Config Settings" for the "Manage Stock" value') ?>
        </li>
        <li>
            <?php echo __('The "qty" field is the "Qty" value') ?>
        </li>
    </ul>
</div>
